In [4]:
#import my other notebook
%run 2.Py-Lists_Vs_Np-Arrays.ipynb
#it not only fetch data from (2.Py-Lists_Vs_Np-Arrays.ipynb), it also fetch data from other notebook whiched it fatch before.

2800
400
1.8012676239013672
0.5300123691558838


In [7]:
arr12=np.arange(24).reshape(6,4)
arr12

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [12]:
arr12[2] #3rd row index 0,1,2

array([ 8,  9, 10, 11])

In [15]:
arr12[:,2] #3rd column index 0,1,2

array([ 2,  6, 10, 14, 18, 22])

In [22]:
arr12[:,2:4]

array([[ 2,  3],
       [ 6,  7],
       [10, 11],
       [14, 15],
       [18, 19],
       [22, 23]])

In [25]:
arr12[3:4,1:4]

array([[13, 14, 15]])

In [27]:
arr12

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

Iteration

In [28]:
for i in arr12:
    print(i)

[0 1 2 3]
[4 5 6 7]
[ 8  9 10 11]
[12 13 14 15]
[16 17 18 19]
[20 21 22 23]


In [29]:
for i in np.nditer(arr12):
    print(i)

0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
