In [18]:
%run 4.Numpy_Operations.ipynb

2800
400
1.6698133945465088
0.7544217109680176
[0 1 2 3]
[4 5 6 7]
[ 8  9 10 11]
[12 13 14 15]
[16 17 18 19]
[20 21 22 23]
0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23


In [19]:
np.median(arr4)

8.5

In [20]:
np.exp(arr4)

array([[  403.42879349,  1096.63315843],
       [ 2980.95798704,  8103.08392758],
       [22026.46579481, 59874.1417152 ]])

In [21]:
arr4.ndim

2

In [22]:
arr4

array([[ 6,  7],
       [ 8,  9],
       [10, 11]])

In [23]:
arr4.ravel()

array([ 6,  7,  8,  9, 10, 11])

In [24]:
arr4.transpose()

array([[ 6,  8, 10],
       [ 7,  9, 11]])

In [25]:
arr5

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [26]:
arr5=np.arange(12,18).reshape(2,3)

In [27]:
arr5

array([[12, 13, 14],
       [15, 16, 17]])

In [28]:
arr3

array([[0, 1, 2],
       [3, 4, 5]])

In [29]:
np.hstack((arr3,arr5)) # Horizontal stack

array([[ 0,  1,  2, 12, 13, 14],
       [ 3,  4,  5, 15, 16, 17]])

# Example
- for adding data from multiple source.
- when we have same column in multiple sources and we need to add data vertically we use `vstack()`

In [30]:
np.vstack((arr3,arr5)) # Vertical stack

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [12, 13, 14],
       [15, 16, 17]])

In [35]:
arr3

array([[0, 1, 2],
       [3, 4, 5]])

In [33]:
np.hsplit(arr3,3) 

[array([[0],
        [3]]),
 array([[1],
        [4]]),
 array([[2],
        [5]])]

In [34]:
np.vsplit(arr3,2) 

[array([[0, 1, 2]]), array([[3, 4, 5]])]

- if error comes in np. then its a static function
- if error comes in array. then its a non-static function