In [5]:
%run 5.Reshaping_Numpy_arrays.ipynb

2800
400
1.3168270587921143
0.5825071334838867
[0 1 2 3]
[4 5 6 7]
[ 8  9 10 11]
[12 13 14 15]
[16 17 18 19]
[20 21 22 23]
0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23


In [6]:
import numpy as np

In [8]:
arr8 = np.arange(24).reshape(6,4)

In [9]:
arr8

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [26]:
arr8[[0,2,4]] # to get 1st 3rd and 6th row of arr8

array([[ 0,  1,  2,  3],
       [ 8,  9, 10, 11],
       [16, 17, 18, 19]])

In [41]:
arr8[:, [0,2]] # to get 1st and 3rd column of arr8

array([[ 0,  2],
       [ 4,  6],
       [ 8, 10],
       [12, 14],
       [16, 18],
       [20, 22]])