In [1]:
import numpy as np

In [2]:
arr = np.random.randint(low=1,high = 100, size= 20).reshape(4,5)

In [3]:
arr

array([[91, 63, 68, 85, 95],
       [87,  6, 78, 26, 82],
       [96, 72, 30, 82,  5],
       [56, 17, 13, 83, 30]])

In [4]:
arr > 50

array([[ True,  True,  True,  True,  True],
       [ True, False,  True, False,  True],
       [ True,  True, False,  True, False],
       [ True, False, False,  True, False]])

In [6]:
#INdexing using Boolean arrays / filtering
arr[arr > 50]

array([91, 63, 68, 85, 95, 87, 78, 82, 96, 72, 82, 56, 83])

In [10]:
arr[(arr>50) & (arr%2!=0)]

array([91, 63, 85, 95, 87, 83])

In [11]:
arr[(arr>50) & (arr%2!=0)] = 0

In [12]:
arr

array([[ 0,  0, 68,  0,  0],
       [ 0,  6, 78, 26, 82],
       [96, 72, 30, 82,  5],
       [56, 17, 13,  0, 30]])