In [1]:
import numpy as np

In [8]:
# Scenario 1

a1 = np.arange(8).reshape(2,4)
a2 = np.arange(8,16).reshape(2,4)

In [13]:
print(a1)
print(a2)

[[0 1 2 3]
 [4 5 6 7]]
[[ 8  9 10 11]
 [12 13 14 15]]


In [14]:
a1

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

In [12]:
a2

array([[ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [15]:
a1 + a2

array([[ 8, 10, 12, 14],
       [16, 18, 20, 22]])

In [16]:
a3 = np.arange(9).reshape(3,3)
a4 = np.arange(3).reshape(1,3)

In [17]:
print(a3,a4)

[[0 1 2]
 [3 4 5]
 [6 7 8]] [[0 1 2]]


In [18]:
a3+a4

array([[ 0,  2,  4],
       [ 3,  5,  7],
       [ 6,  8, 10]])

The term broadcasting describes how NumPy treats arrays with different shapes during arithmetic operations. Subject to certain constraints, the smaller array is “broadcast” across the larger array so that they have compatible shapes.

## Rules for Broadcasting

In [19]:
# if x=m and y=n, operation will take place
a1 = np.arange(8).reshape(2,4)
a2 = np.arange(8,16).reshape(2,4)

a1 + a2 

array([[ 8, 10, 12, 14],
       [16, 18, 20, 22]])

In [22]:
# if x=1 and y=n then also operation will take place(Same Dimension)
a3 = np.arange(9).reshape(3,3)
a4 = np.arange(3).reshape(1,3)

print(a3)
print(a4)


[[0 1 2]
 [3 4 5]
 [6 7 8]]
[[0 1 2]]


In [23]:
a3 + a4

array([[ 0,  2,  4],
       [ 3,  5,  7],
       [ 6,  8, 10]])

In [27]:
# if x=1 and y!=n then operation will not take place(Same Dimension)
a5=np.arange(3).reshape(1,3)
a6=np.arange(16).reshape(4,4)

print(a5)
print(a6)

# ValueError: operands could not be broadcast together with shapes (1,3) (4,4) 


[[0 1 2]]
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]


In [28]:
a5 + a6

ValueError: operands could not be broadcast together with shapes (1,3) (4,4) 

In [32]:
# if x=1 and n = 1 then y==m, this operation also take place

a7=np.arange(3).reshape(1,3)
a8=np.arange(3).reshape(3,1)

print(a7)
print(a8)

[[0 1 2]]
[[0]
 [1]
 [2]]


In [33]:
a7 + a8

array([[0, 1, 2],
       [1, 2, 3],
       [2, 3, 4]])

In [35]:
# if x=1 and y=1, then this operation also take place
a9=np.arange(1).reshape(1,1)
a10=np.arange(20).reshape(4,5)

print(a9)
print(a10)

[[0]]
[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]


In [36]:
a9 + a10

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [39]:
# if they are of different dimensions

a11 = np.arange(4)
a12 = np.arange(20).reshape(5,4)

print(a11)
print(a12)

[0 1 2 3]
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]]


In [40]:
a11 + a12

array([[ 0,  2,  4,  6],
       [ 4,  6,  8, 10],
       [ 8, 10, 12, 14],
       [12, 14, 16, 18],
       [16, 18, 20, 22]])